const ActionTypes = {
  LOG_IN: "LOG_IN",
  LOG_USER: "LOG_USER",
  FETCH_PRODUCT_LINES: "FETCH_PRODUCT_LINES",
  FETCH_PRODUCT: "FETCH_PRODUCT",
  FETCH_PRODUCT_BY_LINE: "FETCH_PRODUCT_BY_LINE"
};

export default ActionTypes;
