const ActionTypes = {
  LOG_IN: "LOG_IN",
  LOG_USER: "LOG_USER",
  FETCH_PRODUCT_LINES: "FETCH_PRODUCT_LINES",
  FETCH_PRODUCT: "FETCH_PRODUCT",
  FETCH_PRODUCT_BY_LINE: "FETCH_PRODUCT_BY_LINE",
  ADD_PRODUCT_LINE: "ADD_PRODUCT_LINE",
  ADD_PRODUCT: "ADD_PRODUCT",
  DEL_PRODUCT_LINE: "DEL_PRODUCT_LINE",
  DEL_PRODUCT: "DEL_PRODUCT"
};

export default ActionTypes;
